before_script:
  - hostname
  - whoami
  - pwd
  - ls -la
  - docker --version

stages:
   - build
   - test
   - coverage
   - deploy
#   - test-deployment

build:
  tags:
     - risc
  stage: build
  script: docker build --build-arg LOCAL_USER_ID=`id -u`  --tag citest .

test:
  tags:
     - risc
  stage: test
  script: scripts/run-tests-in-docker.sh
  artifacts:
    paths:
      - coverage
      
pages:
 stage: coverage
 tags:
     - risc
 dependencies:
   - test
 script:
   - mv coverage public/
 artifacts:
   paths:
     - public

deploy:
   tags:
     - risc
   stage: deploy
   script: ./scripts/redeploy.sh

#test-deployment:
#   tags:
#     - risc
#   stage: test-deployment
#   dependencies:
#     - deploy
#   script: ./scripts/test-deployment.sh
